project:
  type: website

website:
  title: "G2 Group 5"
  navbar:
    left: 
      - href: proposal.html
        text: "Proposal"
      - href: poster.qmd
        text: "Poster"
      - sidebar:data
      - sidebar:siteselection
      - href: webmaps.qmd
        text: "Web Maps"
      - href: report.qmd
        text: "Report"
    right:
      - href: about.qmd
        text: "About"
    
  sidebar:
    - id: data
      title: "Data"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - datacollection.qmd
        - datapreparation.qmd
    - id: siteselection
      title: "Site Selection"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - mergers.qmd
        - closures.qmd
    
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

