project:
  type: website

website:
  title: "G2T5: MerGIS"
  navbar:
    left: 
      - href: proposal.html
        text: "Project Proposal"
      - text: "Methodology"
        menu:
        - datacollection.qmd
        - datapreparation.qmd
        - chloropleth.qmd
        - accessibility.qmd
      - href: report.qmd
        text: "Results & Discussion"
      - href: conclusion.qmd
        text: "Lessons Learnt"
      - href: poster.qmd
        text: "Poster"
    right:
      - href: about.qmd
        text: "About"

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

