project:
  type: website

website:
  title: "G2 Group 5"
  navbar:
    left: 
      - href: overview.html
        text: "Overview"
      - href: poster.qmd
        text: "Poster"
      - sidebar:datapreparation
      - sidebar:siteselection
      - href: webmaps.qmd
        text: "Web Maps"
    right:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Us"
    
  sidebar:
    - id: datapreparation
      title: "Data Preparation"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - datapreparation.qmd
        - datapreparation-1.qmd
    - id: siteselection
      title: "Site Selection"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - mergers.qmd
        - closures.qmd
    
format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

