project:
  type: website

website:
  title: "G2T5: MerGIS"
  navbar:
    left: 
      - href: proposal.html
        text: "Proposal"
      - href: poster.qmd
        text: "Poster"
      - sidebar:data
      - href: report.qmd
        text: "Report & Maps"
    right:
      - href: about.qmd
        text: "About"
    
  sidebar:
    - id: data
      title: "Data"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - datacollection.qmd
        - datapreparation.qmd
        - chloropleth.qmd
        - accessibility.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

