---
title: "Lessons Learnt"
editor: visual
---

## Conclusion

In conclusion, the merging of schools in Singapore has brought about an overall decrease in accessibility to schools across Singapore. However, while there was a decrease in accessibility, this change is still minimal as schools that were merged were in close proximity to one another. Should the government need to merge more schools, it would be advisable to continue merging schools that are already in close proximity. The impact of merging schools that are further apart from one another can be observed from the merger of pre-tertiary institutions. However, we acknowledge that as people get older (e.g. primary school students vs pre-tertiary students), they are likely to be more willing to travel a longer distance. 

\

That being said, these mergers may have underlying implications on costs and standard of living which we are unable to observe directly from the visual differences between the maps. One reason for an increase in costs of living is due to the increase in time needed to travel as schools are now further away. Additionally, there may be an increase in costs as people who could previously walk to school now need to take public transport, and even for people who previously took public transport, the distance they need to travel now may be greater than before. 

\

However, our group still believes that even though there was a decrease in accessibility, the changes were minimal, hence the equity of access to schools in Singapore is still maintained.
